cc4401Inventory/cc4401Inventory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('user/', include('usersApp.urls')),
    path('admin/', include('adminApp.urls')),
    path('article/', include('articlesApp.urls')),
    path('loans/', include('loansApp.urls')),
    path('space/', include('spacesApp.urls')),
    path('reservations/', include('reservationsApp.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cc4401Inventory/mainApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('articles/', views.landing_articles, name='landing_articles'),
    path('spaces/', views.landing_spaces, name='landing_spaces'),
    path('spaces/<str:date>/<str:filter>', views.landing_spaces, name='landing_spaces_filter'),
    path('search/', views.search, name='search'),
    path('create_reservation/', views.crear_reserva1, name='create_reservation'),
]

cc4401Inventory/spacesApp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<int:space_id>', views.space_data, name='space_data'),
    path('<int:space_id>/edit', views.space_data_admin, name='space_data_admin'),
    path('<int:space_id>/edit_name', views.space_edit_name, name='space_edit_name'),
    path('<int:space_id>/edit_image', views.space_edit_image, name='space_edit_image'),
    path('<int:space_id>/edit_description', views.space_edit_description, name='space_edit_description'),
    path('<int:space_id>/edit_capacity', views.space_edit_capacity, name='space_edit_capacity'),
    path('request', views.space_request, name='space_request'),
]

cc4401Inventory/spacesApp/models.py
from django.db import models
from mainApp.models import Item


class Space(Item):
    STATES = (
        ('D', 'Disponible'),
        ('P', 'En préstamo'),
        ('R', 'En reparación')
    )
    state = models.CharField(max_length=1, choices=STATES)
    capacity = models.IntegerField()

cc4401Inventory/spacesApp/views.py
from django.shortcuts import render, redirect
from spacesApp.models import Space
from django.db import models
from datetime import datetime, timedelta
from django.utils.timezone import localtime
import random, os
import pytz
from django.contrib import messages
from django.shortcuts import render
from django.utils.timezone import localtime
import datetime
from articlesApp.models import Article
from reservationsApp.models import Reservation
from django.contrib.auth.decorators import login_required



@login_required
def space_data(request, space_id, date=None):
    try:
        space = Space.objects.get(id=space_id)

        if date:
            current_date = date
            current_week = datetime.datetime.strptime(current_date, "%Y-%m-%d").date().isocalendar()[1]
        else:
            try:
                current_week = datetime.datetime.strptime(request.GET["date"], "%Y-%m-%d").date().isocalendar()[1]
                current_date = request.GET["date"]
            except:
                current_week = datetime.date.today().isocalendar()[1]
                current_date = datetime.date.today().strftime("%Y-%m-%d")

        reservations = Reservation.objects.filter(starting_date_time__week=current_week, state__in=['P', 'A'], space=space)
        colores = {'A': 'rgba(0,153,0,0.7)',
                   'P': 'rgba(51,51,204,0.7)'}

        res_list = []
        for i in range(5):
            res_list.append(list())
        for r in reservations:
            reserv = []
            reserv.append(r.space.name)
            reserv.append(r.space.id)
            reserv.append(localtime(r.starting_date_time).strftime("%H:%M"))
            reserv.append(localtime(r.ending_date_time).strftime("%H:%M"))
            reserv.append(colores[r.state])
            res_list[r.starting_date_time.isocalendar()[2] - 1].append(reserv)

        move_controls = list()
        move_controls.append(
            (datetime.datetime.strptime(current_date, "%Y-%m-%d") + datetime.timedelta(weeks=-4)).strftime("%Y-%m-%d"))
        move_controls.append(
            (datetime.datetime.strptime(current_date, "%Y-%m-%d") + datetime.timedelta(weeks=-1)).strftime("%Y-%m-%d"))
        move_controls.append(
            (datetime.datetime.strptime(current_date, "%Y-%m-%d") + datetime.timedelta(weeks=1)).strftime("%Y-%m-%d"))
        move_controls.append(
            (datetime.datetime.strptime(current_date, "%Y-%m-%d") + datetime.timedelta(weeks=4)).strftime("%Y-%m-%d"))

        delta = (datetime.datetime.strptime(current_date, "%Y-%m-%d").isocalendar()[2]) - 1
        monday = ((datetime.datetime.strptime(current_date, "%Y-%m-%d") - datetime.timedelta(days=delta)).strftime(
            "%d/%m/%Y"))


        context = {
            'space': space,
            'reservations': res_list,
            'current_date': current_date,
            'controls': move_controls,
            'actual_monday': monday
        }

        return render(request, 'space_data.html', context)
    except Exception as e:
        print(e)
        return redirect('/')


def verificar_horario_habil(horario):
    if horario.isocalendar()[2] > 5:
        return False
    
    if horario.hour < 9 or horario.hour > 18:
        return False

    return True


@login_required
def space_request(request):
    if request.method == 'POST':
        space = Space.objects.get(id = request.POST['space_id'])

        if request.user.enabled:
            try:
                string_inicio = request.POST['fecha_inicio'] + " " + request.POST['hora_inicio']
                print(string_inicio)
                start_date_time = datetime.datetime.strptime(string_inicio, '%Y-%m-%d %H:%M')
                string_fin = request.POST['fecha_fin'] + " " + request.POST['hora_fin']
                print(string_fin)
                end_date_time = datetime.datetime.strptime(string_fin, '%Y-%m-%d %H:%M')

                if start_date_time > end_date_time:
                    messages.warning(request, 'La reserva debe terminar después de iniciar.')
                elif start_date_time < datetime.datetime.now() + timedelta(hours=1):
                    messages.warning(request, 'Los pedidos deben ser hechos al menos con una hora de anticipación.')
                elif start_date_time.date() != end_date_time.date():
                    messages.warning(request, 'Los pedidos deben ser devueltos el mismo día que se entregan.')
                elif not verificar_horario_habil(start_date_time) or not verificar_horario_habil(end_date_time):
                    messages.warning(request, 'Los pedidos deben ser hechos en horario hábil.')
                else:
                    res = Reservation(space=space, starting_date_time=start_date_time, ending_date_time=end_date_time,
                                user=request.user)
                    res.save()
                    messages.success(request, 'Pedido realizado con éxito')
            except Exception as e:
                messages.warning(request, 'Ingrese una fecha y hora válida.')
        else:
            messages.warning(request, 'Usuario no habilitado para pedir préstamos')

        return redirect('/space/' + str(space.id))


@login_required
def space_data_admin(request, space_id):
    if not request.user.is_staff:
        return redirect('/')
    else:
        try:
            space = Space.objects.get(id=space_id)
            context = {
                'space': space
            }
            return render(request, 'space_data_admin.html', context)
        except:
            return redirect('/')



@login_required
def space_edit_name(request, space_id):
    if request.method == "POST":
        a = Space.objects.get(id=space_id)
        a.name = request.POST["name"]
        a.save()
    return redirect('/space/'+str(space_id)+'/edit')


@login_required
def space_edit_image(request, space_id):
    if request.method == "POST":
        u_file = request.FILES["image"]
        extension = os.path.splitext(u_file.name)[1]
        a = Space.objects.get(id=space_id)
        a.image.save(str(space_id)+"_image"+extension, u_file)
        a.save()

    return redirect('/space/' + str(space_id) + '/edit')



@login_required
def space_edit_description(request, space_id):
    if request.method == "POST":
        a = Space.objects.get(id=space_id)
        a.description = request.POST["description"]
        a.save()

    return redirect('/space/' + str(space_id) + '/edit')


@login_required
def space_edit_capacity(request, space_id):
    if request.method == "POST":
        a = Space.objects.get(id=space_id)
        a.capacity = request.POST["capacity"]
        a.save()

    return redirect('/space/' + str(space_id) + '/edit')

cc4401Inventory/spacesApp/templates/calendario.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'mainApp/css/schedule_reset.css' %}"> <!-- CSS reset -->
</head>

<div class="col-4">
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <label class="input-group-text" for="inputGroupSelect01">Espacios</label>
        </div>
        <form id="myform" method="post" action="{% url 'landing_spaces' date=current_date filter=filter_calendar %}">
            {% csrf_token %}
            <select id="calendarFilter" name="espacios" class="custom-select">
                <option value="A" {% if filter_calendar == "A" %}selected{% endif %}>---</option>
                {% for i in spaces %}
                    <option value="{{ i.name }}"
                            {% if filter_calendar == i.name %}selected{% endif %}>{{ i.name }}</option>
                {% endfor %}
            </select>
        </form>
    </div>

    <div class="center-column">
        <ul class="list-horizontal">
            <li class="a"><span style="font-size: 1em">Aceptado</span></li>
            <li class="p"><span style="font-size: 1em">Pendiente</span></li>
        </ul>
    </div>

</div>


<div class="cd-schedule loading">
    <div class="timeline" id="timeline">
        <ul>
            <li><span>09:00</span></li>
            <li><span>09:30</span></li>
            <li><span>10:00</span></li>
            <li><span>10:30</span></li>
            <li><span>11:00</span></li>
            <li><span>11:30</span></li>
            <li><span>12:00</span></li>
            <li><span>12:30</span></li>
            <li><span>13:00</span></li>
            <li><span>13:30</span></li>
            <li><span>14:00</span></li>
            <li><span>14:30</span></li>
            <li><span>15:00</span></li>
            <li><span>15:30</span></li>
            <li><span>16:00</span></li>
            <li><span>16:30</span></li>
            <li><span>17:00</span></li>
            <li><span>17:30</span></li>
            <li><span>18:00</span></li>
        </ul>
    </div> <!-- .timeline -->
    <div id="line-container" class="line-container">
        <div id="line" class="clock"></div>
        <div class="message" id="message"></div>
    </div>
    <div class="events" id="events">
        <ul>
            <li class="events-group">
                <div class="top-info"><span>Lunes</span></div>

                <ul>
                    {% for r in reservations.0 %}

                        <li class="single-event" data-start="{{ r.2 }}" data-end="{{ r.3 }}" bgcolor="{{ r.4 }}">
                            <a onClick="location.href = '{% url 'space_data' r.1 %}';">
                                <em class="event-name">{{ r.0 }}</em>
                            </a>
                        </li>

                    {% endfor %}

                </ul>
            </li>

            <li class="events-group">
                <div class="top-info"><span>Martes</span></div>

                <ul>

                    {% for r in reservations.1 %}

                        <li class="single-event" data-start="{{ r.2 }}" data-end="{{ r.3 }}" bgcolor="{{ r.4 }}">
                            <a onClick="location.href = '{% url 'space_data' r.1 %}';">
                                <em class="event-name">{{ r.0 }}</em>
                            </a>
                        </li>

                    {% endfor %}
                </ul>
            </li>

            <li class="events-group">
                <div class="top-info"><span>Miércoles</span></div>

                <ul>
                    {% for r in reservations.2 %}

                        <li class="single-event" data-start="{{ r.2 }}" data-end="{{ r.3 }}" bgcolor="{{ r.4 }}">
                            <a onClick="location.href = '{% url 'space_data' r.1 %}';">
                                <em class="event-name">{{ r.0 }}</em>
                            </a>
                        </li>

                    {% endfor %}
                </ul>
            </li>

            <li class="events-group">
                <div class="top-info"><span>Jueves</span></div>

                <ul>
                    {% for r in reservations.3 %}

                        <li class="single-event" data-start="{{ r.2 }}" data-end="{{ r.3 }}" bgcolor="{{ r.4 }}">
                            <a onClick="location.href = '{% url 'space_data' r.1 %}';">
                                <em class="event-name">{{ r.0 }}</em>
                            </a>
                        </li>

                    {% endfor %}
                </ul>
            </li>

            <li class="events-group">
                <div class="top-info"><span>Viernes</span></div>

                <ul>
                    {% for r in reservations.4 %}

                        <li class="single-event" data-start="{{ r.2 }}" data-end="{{ r.3 }}" bgcolor="{{ r.4 }}">
                            <a onClick="location.href = '{% url 'space_data' r.1 %}';">
                                <em class="event-name">{{ r.0 }}</em>
                            </a>
                        </li>

                    {% endfor %}
                </ul>
            </li>
        </ul>

    </div>

    <div class="week-select" id="week-select">
        <div style="text-align: center; margin-right: auto; margin-left: auto; width: 200px; font-size: 18px">
            <form action="" method="get" class="selectform">
                <a href="{% url 'landing_spaces' date=controls.0 %}" role="button"><i
                        class="fas fa-angle-double-left"></i></a>
            </form>
            <form action="" method="get" class="selectform">
                <a href="{% url 'landing_spaces' date=controls.1 %}" role="button"><i
                        class="fas fa-angle-left"></i></a>
            </form>
            <form action="" method="get" class="selectform">
                <a href="{% url 'landing_spaces' date=controls.2 %}" role="button"><i
                        class="fas fa-angle-right"></i></a>
            </form>
            <form action="" method="get" class="selectform">
                <a href="{% url 'landing_spaces' date=controls.3 %}" role="button"><i
                        class="fas fa-angle-double-right"></i></a>
            </form>
        </div>

    </div>


    <div class="event-modal">
        <header class="header">
            <div class="content">
                <span class="event-date"></span>
                <h3 class="event-name"></h3>
            </div>

            <div class="header-bg"></div>
        </header>

        <div class="body">
            <div class="event-info"></div>
            <div class="body-bg"></div>
        </div>

        <a href="#0" class="close">Close</a>
    </div>

    <div class="cover-layer"></div>
</div> <!-- .cd-schedule -->

<script src="{% static 'js/modernizr.js' %}"></script>
<script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script> <!-- Resource jQuery -->

cc4401Inventory/spacesApp/templates/space_data.html
{% extends 'application_layout.html' %}

{% load static %}

{% block title %}
  Ficha del artículo: {{ space.name }}
{% endblock %}


{% block body %}

  <div class="row">
    <div class="col-md-4 offset-1">

      <div class="row">
        <h1 class="article-name">
          {{ space.name }}
        {% if space.state == "D" %}
            <span class="badge badge-pill badge-success"><i class="fas fa-chevron-left"></i> {{  space.get_state_display }}</span>
          {% elif space.state == "P" %}
            <span class="badge badge-pill badge-primary"><i class="fas fa-chevron-left"></i> {{  space.get_state_display }}</span>
          {% elif space.state == "R" %}
            <span class="badge badge-pill badge-warning"><i class="fas fa-chevron-left"></i> {{  space.get_state_display }}</span>
          {% endif %}
         </h1>
      </div>
        {% if space.image %}
            <img src= " {% static space.image.url %}" class="img-fluid" alt="Foto" style="height: 400px" />
        {% else %}
            <img class="card-img-top" src="{% static 'img/items/default_article.jpg' %}" alt="Card image cap">
        {% endif %}

      <div class="card">
        <div class="card-header article-description-title">Descripción</div>
        <div class="card-body">
          <p class="card-text">{{ space.description }}</p>
        </div>
      </div>

      <div class="card">
        <div class="card-header article-description-title">Capacidad</div>
        <div class="card-body">
          <p class="card-text">{{ space.capacity }}</p>
        </div>
      </div>
    </div>

    <div class = "col-md-5 offset-1">
      <h3 class="block-title">Solicitar reserva</h3>
      <div class="row" style="margin-top: 2em;">
        <div class="col-6 offset-3 schedule-current-week" style="text-align: center;">
          <div class="alert alert-info">
            <p>Estás viendo la semana del lunes <b>{{ actual_monday }}</b></p>
          </div>
        </div>
      {% include '_schedule.html' %}
    </div>


    </div>

  </div>
</div>
{% endblock %}

cc4401Inventory/spacesApp/templates/space_data_admin.html
{% extends 'application_layout.html' %}

{% load static %}

{% block title %}
 Editando artículo: {{ space.name }}
{% endblock %}


{% block body %}
<div class = "container" style="margin-top: 20px">
  <div class="row">
  <div class="col-md-2">
  </div>
    <div class="col-md-8">

      <div class="row"><h1> {{ space.name }}<!-- Button trigger modal -->
<button type="button" class="btn btn-light" data-toggle="modal" data-target="#editName">
  <i class="fas fa-edit"></i>
</button>
        {% if space.state == "D" %}
            <span class="badge badge-pill badge-success"><i class="fas fa-chevron-left"></i> {{  space.get_state_display }}</span>
          {% elif space.state == "P" %}
            <span class="badge badge-pill badge-primary"><i class="fas fa-chevron-left"></i> {{  space.get_state_display }}</span>
          {% elif space.state == "R" %}
            <span class="badge badge-pill badge-warning"><i class="fas fa-chevron-left"></i> {{  space.get_state_display }}</span>
          {% endif %}
      </h1>
      </div>

      <div>
          {% if space.image %}
            <img src= " {% static space.image.url %}" class="img-fluid" alt="Foto" style="height: 400px" />
        {% else %}
            <img class="card-img-top" src="{% static 'img/items/default_article.jpg' %}" alt="Card image cap">
        {% endif %}
          <button type="button" class="btn btn-light" data-toggle="modal" data-target="#editImage">
            <i class="fas fa-edit"></i>
      </button></div>
      <div style="margin-bottom: 30px">
          <div style ="border:1px dashed darkgrey;border-radius: 5px;padding: 5px;height:120px;width:calc(100% - 60px); display: inline-block; overflow: scroll;">{{ space.description }}</div>
          <button type="button" class="btn btn-light" data-toggle="modal" data-target="#editDescription" style="margin-bottom:1.6rem">
              <i class="fas fa-edit"></i>
          </button>
      </div>
      <div style="margin-bottom: 30px">
        <div style ="border:1px dashed darkgrey;border-radius: 5px;padding: 5px;height:120px;width:calc(100% - 60px); display: inline-block;">{{ space.capacity }}</div>
        <button type="button" class="btn btn-light" data-toggle="modal" data-target="#editCapacity" style="margin-bottom:1.6rem">
            <i class="fas fa-edit"></i>
        </button>
    </div>
    </div>
  <div class="col-md-2">
  </div>



  </div>



    <!---  MODALES PARA EDICION DE LOS CAMPOS --->


        <!-- Nombre -->
    <div class="modal fade" id="editName" tabindex="-1" role="dialog" aria-labelledby="editNameLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="editNameLabel">Editar Nombre del Espacio</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
            <form action="edit_name" method="post">
                {% csrf_token %}
          <div class="modal-body">
            <input name="name" class="form-control" type="text" placeholder="Ingrese Nombre">
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
          </div>
            </form>
        </div>
      </div>
    </div>



    <!-- Imagen -->
    <div class="modal fade" id="editImage" tabindex="-1" role="dialog" aria-labelledby="editImageLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="editImageLabel">Editar Imagen del Espacio</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
            <form action="edit_image" method="post" enctype="multipart/form-data">
                {% csrf_token %}
          <div class="modal-body">
            <label for="editImageControl">Subir Imagen</label>
            <input type="file" class="form-control-file" id="editImageControl" name="image">
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
          </div>
            </form>
        </div>
      </div>
    </div>

    <!-- Descripcion -->
    <div class="modal fade" id="editDescription" tabindex="-1" role="dialog" aria-labelledby="editDescriptionLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="editDescriptionLabel">Editar Descripción del Espacio</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
            <form action="edit_description" method="post">
                {% csrf_token %}
          <div class="modal-body">
            <div class="form-group">
                <label for="textarea1">Ingrese Descripción del artículo</label>
                <textarea name="description" class="form-control" id="textarea1" rows="4">{{ space.description }}</textarea>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
          </div>
            </form>
        </div>
      </div>
    </div>

    <!-- Capacidad -->
    <div class="modal fade" id="editCapacity" tabindex="-1" role="dialog" aria-labelledby="editCapacityLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="editCapacityLabel">Editar Capacidad del Espacio</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
            <form action="edit_capacity" method="post">
                {% csrf_token %}
              <div class="modal-body">
                <div class="form-group">
                    <label for="">Ingrese Capacidad del artículo</label>
                    <input type="number" name="capacity" class="form-control" id="numberInput" value="{{space.capacity}}"></textarea>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Guardar Cambios</button>
              </div>
            </form>
        </div>
      </div>
    </div>


</div>
{% endblock %}